import ThemeProviderWrapper from "@/providers/ThemeProviderWrapper";
import type { Metadata } from "next";
import { Gloock, Montserrat } from "next/font/google";
import "./globals.css";

const montserrat = Montserrat({
    variable: "--montserrat",
    subsets: ["latin"],
});

const gloock = Gloock({
    variable: "--gloock",
    weight: "400",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" suppressHydrationWarning>
            <body
                className={`${montserrat.variable} ${gloock.variable} antialiased bg-zinc-100 dark:bg-zinc-900`}
            >
                <ThemeProviderWrapper>{children}</ThemeProviderWrapper>
            </body>
        </html>
    );
}
